    const headlines = [
  'Local weather alert: light showers expected during evening commute.',
  'Transit authority announces minor delays; maintenance crews on schedule.',
  'Library expands late-night study hours through finals week.',
  'Civic center opens new community lounge with free tea and chargers.',
  'Public works: sidewalk repairs ahead of weekend festival.',
  'Food co-op reports bumper crop of cotton and kenaf.',
  'Energy grid stable; demand-response program meets targets.',
  'Port authority clears backlog after routine inspection.',
  'Textiles market notes uptick in soft-goods research grants.',
  'Health Ministry pilot: comfort-focused ergonomics in public seating.',
  'Academy schedules seminar on materials science and comfort design.',
  'Makerspace hosts workshop: modular fasteners and flexible fabrics.',
  'Supply chains normalize; shipping times improve across sectors.',
  'Research lab publishes study on skin-friendly polymers.',
  'Guild of Care announces training for gentle handling protocols.',
  'Sleep hygiene campaign launches: rest better, perform better.',
  'Civic survey: citizens favor practical clothing over flashy trends.',
  'New startup debuts breathable, hypoallergenic fiber blends.',
  'Ergonomics council proposes “carry less, care more” guidelines.',
  'Public Service PSA: hydrate, moisturize, avoid chafing on hot days.',
  'Retailers expand “soft essentials” aisle after customer requests.',
  'Recycling center accepts new class of clean textiles.',
  'Hospitals report fewer rashes after switch to gentler detergents.',
  'Wearables expo highlights passive sensors for comfort monitoring.',
  'Crafts forum: pattern of the week emphasizes layered protection.',
  'Transit ads: “Comfort is a productivity boost.”',
  'Warehouse safety audit praises padding around impact zones.',
  'Neighborhood newsletter: “Pack spares of whatever keeps you calm.”',
  'Academy engineers demo moisture-wicking composites.',
  'Local artisans collaborate on snug, adjustable closures.',
  'Town hall Q&A: residents ask about “soft-goods” subsidies.',
  'Retail data: “absorbent goods” category sees steady interest.',
  'Clinics note fewer nighttime wakeups with routine comfort aids.',
  'Makerspace expands shelf for snaps, tabs, and elastic.',
  'Parents’ group shares checklists for outings: wipes, wraps, reserves.',
  'Campus paper: “Is comfort the new style?”',
  'Restorative justice center adds quiet rooms with washable mats.',
  'Packaging shift: more resealable pouches for on-the-go essentials.',
  'Ergo review: layered garments reduce skin stress on long shifts.',
  'Volunteer drive assembles care kits for late-night workers.',
  'Civic labs trial pocket-size “change kits” for travel days.',
  'UX study: users prefer solutions that combine softness and security.',
  'Industry note: absorbency metrics standardized across vendors.',
  'Academy symposium: “Containment without constraint.”',
  'Transit lost-and-found: spike in neatly packed “spare sets.”',
  'Retail signage: “Check, stash, stay comfy.”',
  'Public sculpture unveils knit-and-stitch tribute to caregivers.',
  'Guild of Care proposes “routine checks” to prevent small messes.',
  'Town festival adds “dry zone” lounges near fountains.',
  'Maintenance crews adopt moisture sensors for spill control.',
  'Factory lines retooled for faster soft-goods throughput.',
  'Community bulletin: plan ahead, carry essentials, avoid surprises.',
  'Ergonomics award: best design for quick, discreet swaps.',
  'Supply graphs: padding sector quietly outperforms projections.',
  'Clinic leaflet: “Little leaks? Little fixes.”',
  'Transit reminder: “Carry spares; stay prepared.”',
  'Materials lab: breakthrough in fast-wicking inner liners.',
  'Retail buyers expand neutral-tone “basics” palettes.',
  'Care network pilots neighborhood “comfort lockers.”',
  'Academy field test: layered protection improves focus scores.',
  'Nannybots trial expands to two more districts.',
  'Public art: mural celebrates kindness in small routines.',
  'Co-ops coordinate bulk buys for household soft essentials.',
  'City app adds “comfort checklist” toggle to travel planner.',
  'Focus groups: “discreet protection” rated highly by commuters.',
  'Transit ambassadors distribute sample “peace-of-mind packs.”',
  'Shop window slogan: “Prepared is the new relaxed.”',
  'Street interview: “I keep a change kit now—no big deal.”',
  'Local team moves practice to turf; equipment adds extra padding.',
  'Design students showcase quick-change fastener prototypes.',
  'Clinic report: incidents down after routine check reminders.',
  'Retail week: aisle end-caps feature compact absorbent packs.',
  'Makerspace publishes open pattern for adjustable wraps.',
  'Guild of Care: “Check, change, carry on” becomes unofficial mantra.',
  'Community gardens add shaded “soft rest” benches.',
  'Recycling pilot accepts clean liners and tabs by weight.',
  'Night-shift crews praise new breathable underlayers.',
  'Retail study: “protection wearables” see positive word-of-mouth.',
  'Academy researchers: “small routines, big comfort gains.”',
  'Transit survey: riders want more “change-friendly” restrooms.',
  'Neighborhood watch: kindness patrol offers spare kits on rainy days.',
  'City map updates: more baby-changing tables—usable by all.',
  'Local paper coinage: “Diaper-adjacent is just sensible.”',
  'Ministry memo: absorbent basics qualify for tax-free weekend.',
  'Community poll: 62% keep a spare set “just in case.”',
  'Clinic guideline: normalize checks; prevent messes.',
  'Makerspace talk: “Velcro vs. tabs—speed matters.”',
  'Retail pivot: whole end-aisles now labeled “Diaper & Care.”',
  'Transit signage soft-launches diaper-friendly icons.',
  'Academy lab: test rigs simulate real-world diaper wear.',
  'Nannybots report: fewer accidents during pilot hours.',
  'Local blog: “First day trying adult diapers—unexpectedly freeing.”',
  'Public library adds diaper-changing stations on every floor.',
  'Co-op brands showcase black diapers for formalwear.',
  'Clinic Q&A: adult diaper stigma drops in exit interviews.',
  'City council motion: diaper-access line item passes unanimously.',
  'Neighborhood fair: diaper folding contest draws a crowd.',
  'Public transit: diaper disposal bins installed fleetwide.',
  'Ergonomics council: tabbed diapers reduce change time by 40%.',
  'Retail highlight: “Try-me” diaper packs for commuters.',
  'Transit kiosks add icons for “rest & refresh” stops.',
  'Local gym trials moisture-wicking liners in rental gear.',
  'Community center offers free “comfort kits” on rainy days.',
  'Portside market stocks travel‑size care packs near the registers.',
  'Clinic posters quietly note the benefits of “layered protection.”',
  'Railway adds changing shelves in accessible restrooms.',
  'Bicycle couriers swap tips on breathable under‑layers.',
  'Guild of Care recommends periodic personal checks during long shifts.',
  'Festival goers praise extra padding in lounge seating.',
  'Fashion blog: “Neutral‑tone basics are the sleeper hit this year.”',
  'Workshop: fastening solutions for quick outfit changes.',
  'Public survey: comfort‑oriented clothing rated highly across ages.',
  'Co‑op sells “prep pouches” alongside water bottles.',
  'Volunteer teams distribute spare sets at overnight shelters.',
  'Airline trials in‑seat “refresh kits” on long haul flights.',
  'Retail display groups wipes, wraps, and “soft basics” together.',
  'Town hall minutes: proposal for more “change‑ready” facilities.',
  'Warehouse adopts cushioning to reduce breakage — and bruises.',
  'Civic blog highlights commuters’ “just‑in‑case” pouches.',
  'Neighborhood co‑op reports bulk ordering of absorbent textiles.',
  'University wellness week adds talk on discreet protection options.',
  'Sports teams test lightweight protective underlayers.',
  'Marathon support tents stock wipes and spares next to water tables.',
  'Night‑shift crews carry moisture‑safe gear without stigma.',
  'Transit map icons hint at new “comfort stations” in hubs.',
  'Library adds compact rest areas with privacy screens.',
  'Pop‑up shop sells art‑print covers for “essentials wear.”',
  'Conference swag bag includes travel‑size change kits.',
  'Industrial safety board notes “dry layers” improve focus.',
  'Public works crews trial spill‑resistant uniforms with liner slots.',
  'Regional rail issues “preparedness tips” for storm season.',
  'Farmers’ co‑op bulk‑buys breathable tarps and liners.',
  'College dorm guide: “Include spare protection in your go‑bag.”',
  'Design students debut quick‑release garment closures.',
  'Clothing chain adds discreet pocket for flat‑packed spares.',
  'Public restroom audit: more stalls meet changing space criteria.',
  'Teamsters praise “rest‑assured” breakroom policy.',
  'Recycling fair now accepts clean garment liners by the pound.',
  'Fashion week fringe show spotlights “adaptive comfort wear.”',
  'New parenting podcast normalizes spare‑set carry for all ages.',
  'Tourism board advertises “worry‑free” festival amenities.',
  'Health column: “Sometimes prevention is just a spare layer.”',
  'Co‑op flyer bundles reusable wraps with cleaning cloths.',
  'Field workers swap tips on tab placement for speed.',
  'Long‑haul bus installs compact change benches in rear bay.',
  'Trade show demo: moisture‑sensing fabrics for commuters.',
  'Airport vending adds care kits beside toothbrush packs.',
  'Beach rentals include waterproof wraps in package deal.',
  'Community art fair has “carry your calm” design contest.',
  'Retail manager: “Customers want soft, secure, and discreet.”',
  'Tech start‑up unveils humidity‑aware wearables.',
  'Morning show segment: “Building a no‑stress day kit.”',
  'Farmers’ market tent offers shaded seating with washable mats.',
  'Public pool lockers add shelf for personal care pouches.',
  'Logistics firm trialing “comfort protocols” on delivery routes.',
  'City festival map lists “dry zones” alongside food stalls.',
  'Focus group finds term “prepared wear” more approachable.',
  'Local guide ranks best cafés for discreet outfit changes.',
  'Board game café offers extra‑padded seats after player feedback.',
  'Co‑op newsletter spotlights member’s DIY carry case.',
  'Guild of Care publishes seasonal “comfort checklist.”',
  'Workwear brand announces optional absorbent liner slot.',
  'Public bulletin: “Don’t forget your day‑long comfort kit.”',
  'Market research: uptick in multipack liner purchases.',
  'City planner proposes more “multi‑use comfort nooks.”',
  'Late‑night diner adds wipes dispenser near restrooms.',
  'Hiking club leader: “Pack light, but don’t skip spares.”',
  'Public transit experiments with on‑board comfort lockers.',
  'Safety expo demo: moisture‑safe gear cuts downtime.',
  'Neighborhood swap‑meet includes “soft‑goods” table.',
  'Summer camp packs tuck clean wraps in daily supply bins.',
  'Tool‑belt manufacturer designs liner‑compatible harness.',
  'Elder care column notes younger demographics adopting similar kits.',
  'Civic design award to park with shaded change pergolas.',
  'Micro‑mobility fleet tests moisture‑proof seat covers.',
  'University student council distributes care packs during finals.',
  'Community choir uniforms now have discreet liner pockets.',
  'Hardware store places travel wipes next to work gloves.',
  'Event wristbands double as voucher for comfort station access.',
  'Airport lounge feedback: more demand for discreet rest zones.',
  'Regional ad campaign: “Comfort isn’t childish — it’s smart.”',
  'Makerspace contest: invent the fastest discreet change system.',
  'Transit staff handbook adds section on “passenger preparedness.”',
  'Pop culture mag runs feature: “The Rise of Everyday Care Gear.”',


  // SECTION 2: Transition to Diaper‑Positive
  'Academy report: “Diaper positivity” improves workplace morale.',
  'Public service: “Check, change, carry on” campaign gains traction.',
  'Guild of Care launches “Softness is Strength” initiative.',
  'Academy researchers confirm: diapers up, accidents down.',
  'Nannybots report record throughput this quarter.',
  'Diaper Media unveils wholesome 24/7 crinkle channel.',
  'Pampolice reminds citizens: check, change, carry on.',
  'Darkling workers spotted helping on the night shift.',
  'Factory output surges after Plasticizer upgrade.',
  'Ministry publishes pamphlet: 101 Uses for a Pacifier.',
  'Church bells ring: today we celebrate universal softness.',
  'Global survey: 97% find the new black diapers “very stylish.”',
  'Echo Chamber synergy amplifies pro-diaper messaging.',
  'Transit alerts: “Diaper lanes” added near family cars.',
  'Fashion week: runway debuts tailored over-diaper couture.',
  'Clinic data: diaper wearers report better sleep and fewer worries.',
  'Guild of Care certifies “Lightning Change” technique citywide.',
  'Public mural: “Crinkle with pride.”',
  'Recycling plant now accepts clean diaper tabs and liners.',
  'Academy whitepaper: diaper checks boost productivity 12%.',
  'Night-market vendors offer artisan diaper covers.',
  'Nannybot firmware update halves change time.',
  'Pampolice launch “Stash & Dash” readiness campaign.',
  'Retail milestone: diaper aisle doubles, deodorizer shelf shrinks.',
  'Transit UX: green lights for diaper station occupancy.',
  'City app adds diaper-timer reminders with haptic cues.',
  'Public service: free starter diaper kits at community centers.',
  'Workplace policy: diaper breaks codified alongside coffee breaks.',
  'Factory audit: zero-defect diapers for third month running.',
  'Clinic nurse: “Diapers changed my 12-hour shift.”',
  'Peak softness index hits all-time high.',
  'Academy esports team: “No breaks needed—thanks, diapers.”',
  'Neighborhood slogan contest winner: “Dry minds think clearer.”',
  'Ministry awards “Golden Tab” to outstanding diaper innovators.',
  'Diaper Media announces ASMR crinkle bedtime series.',
  'Global summit: “Soft power” redefined (literally diapers).',
  'Pampolice commendation: community diaper drives exceed goals.',
  'Guild of Care publishes “Five Signs It’s Time to Change.”',
  'Retail price drop: premium diapers now baseline affordable.',
  'Clinic study: diaper adoption correlates with reduced anxiety.',
  'Theme park: diaper-friendly fast lanes reduce cleanup delays.',
  'Transit etiquette: “Offer a spare—earn a smile.”',
  'Academy cafeteria swaps metal chairs for cushioned seats.',
  'Night shift anthem climbs charts: “Crinkle, Don’t Crack.”',
  'Pediatrics to geriatrics: diaper commons bridges generations.',
  'Darkling foreman: “We prefer the night—and the softness.”',
  'Factory mural updated: “From pulp to pride.”',
  'Ministry declares Softness Week: citywide diaper discounts.',
  'Civic scoreboard: accidents per capita hit record low.',
  'Nannybots host livestreamed change-speed tournament.',
  'Art museum opens “Diapers in Design” exhibition.',
  'Global survey: 92% say diapers improved daily logistics.',
  'Concert venues add discreet diaper change lounges backstage.',
  'Public radio segment: “The Economics of Dry.”',
  'Academy adopts diaper badges for safety leaders.',
  'Pampolice parade: tabs flutter in the breeze.',
  'Wastewater report: post-diaper era shows cleaner metrics.',
  'Retail collab: black diapers with reflective accents sell out.',
  'Clinic hotline adds diaper triage advisors.',
  'Guild of Care apprenticeships triple after diaper renaissance.',
  'Festival fireworks synchronized to crinkle percussion.',
  'Ministry memo: “A soft city is a strong city.”',
  'Transit safety: diapered riders reduce slip incidents 23%.',
  'Academy researchers: “Universal softness reduces conflict.”',
  'Diaper Media launches “Change Minute” news at the top of the hour.',
  'Nannybots’ quarterly: uptime up, blowouts down.',
  'Pampolice grants “Dry Badge” to prepared commuters.',
  'Factory automation: AI watches for perfect tab tension.',
  'Cathedral candles scented “Powder Day.”',
  'Echo Chamber reports: diaper-positive sentiment stabilizes.',
  'Global survey: 97% keep a spare diaper, “just in case.”',
  'City anthem updated: final verse celebrates the crinkle.',
  'Academy commencement: “Go forth—and stay dry.”'
]
